### PR TITLE
Fix regression bug with notification type enqueuing as separate notification

### LINKED ISSUE #137: Tests failure after merging #134
Not sure why these didn't get picked up with #134, but there are now a test failure:

```
Testing /var/www/html/web/modules/contrib/localgov_workflows
................F...........                                      28 / 28 (100%)

Time: 05:57.895, Memory: 26.70 MB

There was 1 failure:

1) Drupal\Tests\localgov_workflows_notifications\Kernel\WorkflowNotificationTest::testEnqueueNodes
Failed asserting that 2 matches expected 3.

/var/www/html/vendor/phpunit/phpunit/src/Framework/Constraint/Equality/IsEqual.php:95
/var/www/html/web/modules/contrib/localgov_workflows/modules/localgov_workflows_notifications/tests/src/Kernel/WorkflowNotificationTest.php:178
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
```

We need to get this fixed before the #135 release.

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #137

## What does this change?

Enqueues notifications depending on service contact and notification type, not just on service contact

With #134 a fix was committed that ensures email notifications were aggregated, but this exposed another error. A notification type is designed to use it's own email template and so needs to be enqueued separately. This happened previously as notifications weren't aggregated, now they are they are not separated by type. 

## How to test

There's only one notification type currently defined, so as long as the tests pass I think it's good to merge :smile:

### CODE REVIEW

**Comment by finnlewis** [comment]
Added a separate issue for the ESLint failures: https://github.com/localgovdrupal/localgov_workflows/issues/139

**Review by finnlewis — APPROVED** [review]
Tests pass, (apart from for PHP 8.4)

File: modules/localgov_workflows_notifications/src/WorkflowNotification.php [hunk 1]
```diff
@@ -42,11 +42,11 @@ public function enqueue(ContentEntityInterface $entity, string $type): void {
           continue;
         }
 
-        // Ensure the queue contains only one item for per service contact.
+        // Aggregate notifications by service contact and type.
         $found = FALSE;
         $claimed_items = [];
         while ($queue_item = $queue->claimItem(1)) {
-          if ($queue_item->data->service_contact == $contact->id()) {
+          if ($queue_item->data->service_contact == $contact->id() && $queue_item->data->type == $type) {
```
Comment (Adnan-cds) [inline modules/localgov_workflows_notifications/src/WorkflowNotification.php]: Would you mind using the identity operator (i.e. `===`) for `$type` comparison here.

I am not doing a full review here.  I will leave that for Finn :)  But I thought I will point this one.

Comment (stephen-cox) [reply modules/localgov_workflows_notifications/src/WorkflowNotification.php]: Done :slightly_smiling_face:

Comment (Adnan-cds) [reply modules/localgov_workflows_notifications/src/WorkflowNotification.php]: Thanks :)
